name: Update Contributors

on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次

jobs:
  update_contributors:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Run script to fetch contributor data
      run: python get_contributors.py
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update contributor data in README"
        git push
